# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Study Materials/Sem 7/ADS/Vector-Processor-SOC/SOC_DMA_V2/SOC_DMA_V2.srcs/sources_1/bd/SOC_DMA_V2/ip/SOC_DMA_V2_xbar_0/SOC_DMA_V2_xbar_0.xci
# IP: The module: 'SOC_DMA_V2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Study Materials/Sem 7/ADS/Vector-Processor-SOC/SOC_DMA_V2/SOC_DMA_V2.srcs/sources_1/bd/SOC_DMA_V2/ip/SOC_DMA_V2_xbar_0/SOC_DMA_V2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_DMA_V2_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Study Materials/Sem 7/ADS/Vector-Processor-SOC/SOC_DMA_V2/SOC_DMA_V2.srcs/sources_1/bd/SOC_DMA_V2/ip/SOC_DMA_V2_xbar_0/SOC_DMA_V2_xbar_0.xci
# IP: The module: 'SOC_DMA_V2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Study Materials/Sem 7/ADS/Vector-Processor-SOC/SOC_DMA_V2/SOC_DMA_V2.srcs/sources_1/bd/SOC_DMA_V2/ip/SOC_DMA_V2_xbar_0/SOC_DMA_V2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_DMA_V2_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
