# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Study Materials/Sem 7/ADS/Vector-Processor-SOC/SOC_DMA_V2/Zedboard-Master.xdc

# Block Designs: bd/SOC_DMA_V2/SOC_DMA_V2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2 || ORIG_REF_NAME==SOC_DMA_V2} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_processing_system7_0_0/SOC_DMA_V2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_processing_system7_0_0 || ORIG_REF_NAME==SOC_DMA_V2_processing_system7_0_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_axi_dma_0_0/SOC_DMA_V2_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_axi_dma_0_0 || ORIG_REF_NAME==SOC_DMA_V2_axi_dma_0_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_ps7_0_axi_periph_0/SOC_DMA_V2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_ps7_0_axi_periph_0 || ORIG_REF_NAME==SOC_DMA_V2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_rst_ps7_0_100M_0/SOC_DMA_V2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_rst_ps7_0_100M_0 || ORIG_REF_NAME==SOC_DMA_V2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_axi_smc_0/SOC_DMA_V2_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_axi_smc_0 || ORIG_REF_NAME==SOC_DMA_V2_axi_smc_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_xbar_0/SOC_DMA_V2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_xbar_0 || ORIG_REF_NAME==SOC_DMA_V2_xbar_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_S2MMV2_0_0/SOC_DMA_V2_S2MMV2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_S2MMV2_0_0 || ORIG_REF_NAME==SOC_DMA_V2_S2MMV2_0_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_blk_mem_gen_0_0/SOC_DMA_V2_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_blk_mem_gen_0_0 || ORIG_REF_NAME==SOC_DMA_V2_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_axi_gpio_0_0/SOC_DMA_V2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_axi_gpio_0_0 || ORIG_REF_NAME==SOC_DMA_V2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_axi_gpio_1_0/SOC_DMA_V2_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_axi_gpio_1_0 || ORIG_REF_NAME==SOC_DMA_V2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_axi_gpio_2_0/SOC_DMA_V2_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_axi_gpio_2_0 || ORIG_REF_NAME==SOC_DMA_V2_axi_gpio_2_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_VCU_bd_0_0/SOC_DMA_V2_VCU_bd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_VCU_bd_0_0 || ORIG_REF_NAME==SOC_DMA_V2_VCU_bd_0_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_xlconcat_0_0/SOC_DMA_V2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_xlconcat_0_0 || ORIG_REF_NAME==SOC_DMA_V2_xlconcat_0_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_ila_0_0/SOC_DMA_V2_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_ila_0_0 || ORIG_REF_NAME==SOC_DMA_V2_ila_0_0} -quiet] -quiet

# IP: bd/SOC_DMA_V2/ip/SOC_DMA_V2_auto_pc_0/SOC_DMA_V2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_DMA_V2_auto_pc_0 || ORIG_REF_NAME==SOC_DMA_V2_auto_pc_0} -quiet] -quiet

# XDC: bd/SOC_DMA_V2/SOC_DMA_V2_ooc.xdc
